sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js: #https://github.com/nodejs/LTS/#lts-schedule
  - 7
  - 6
  - node
before_script:
  - npm prune
script:
    - npm test
after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - ./node_modules/.bin/bithound check git@github.com:gregswindle/generator-android-lib.git
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
